version: '3.4'

services:
  nginx:
    image: ${REPOSITORY_ID:-local/$APP}:nginx-${COMMIT_ID:-latest}
    build:
      context: .
      dockerfile: dockerfile
      target: nginx
    container_name: nginx
    hostname: nginx
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1/stub_status"]
      interval: 1m30s
      timeout: 20s
      retries: 10
    ports:
      - "8080:80"
    restart: unless-stopped
